-- Drop table if exists
DROP TABLE airlines;
DROP TABLE airports;
DROP TABLE flights;

-- Create table 
CREATE TABLE airlines (
	IATA_CODE VARCHAR,
	AIRLINE VARCHAR
);

CREATE TABLE airports (
IATA_CODE VARCHAR,
AIRPORT VARCHAR,
CITY VARCHAR,
STATE VARCHAR,
COUNTRY VARCHAR,
LATITUDE VARCHAR,
LONGITUDE VARCHAR
);

CREATE TABLE flights (
YEAR INT,
MONTH INT,
DAY INT,
DAY_OF_WEEK INT,
AIRLINE VARCHAR,
FLIGHT_NUMBER INT,
TAIL_NUMBER INT,
ORIGIN_AIRPORT VARCHAR,
DESTINATION_AIRPORT VARCHAR,
SCHEDULED_DEPARTURE INT, 
DEPARTURE_TIME INT,
DEPARTURE_DELAY INT,
TAXI_OUT INT,
WHEELS_OFF INT,
SCHEDULED_TIME INT,
ELAPSED_TIME INT,
AIR_TIME INT,
DISTANCE INT,
TAXI_IN INT,
SCHEDULED_ARRIVAL INT,
ARRIVAL_TIMEWHEELS_ON INT,
ARRIVAL_DELAYARRIVAL_TIME INT,
DIVERTED INT,
CANCELLED INT,
CANCELLATION_REASON VARCHAR,
AIR_SYSTEM_DELAY INT,
SECURITY_DELAY INT,
AIRLINE_DELAY INT,
LATE_AIRCRAFT_DELAY INT,
WEATHER_DELAY INT
);


SELECT * FROM airlines;
SELECT * FROM airports;
SELECT * FROM flights;